# Site settings
author: Steven Zych
title: The Steven Zych Python Experience
header-img: img/home-bg.png
email: stevenpzych@gmail.com
copyright_name: Steven Zych
description: > # this means to ignore newlines until "baseurl:"
  It's a blog!
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  stevenzych

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
